export interface Pais {
  value: string
  label: string
}

export const PAISES: Pais[] = [
  { value: 'BR', label: 'Brasil' },
  { value: 'AF', label: 'Afeganistão' },
  { value: 'ZA', label: 'África do Sul' },
  { value: 'AL', label: 'Albânia' },
  { value: 'DE', label: 'Alemanha' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AG', label: 'Antígua e Barbuda' },
  { value: 'SA', label: 'Arábia Saudita' },
  { value: 'DZ', label: 'Argélia' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armênia' },
  { value: 'AU', label: 'Austrália' },
  { value: 'AT', label: 'Áustria' },
  { value: 'AZ', label: 'Azerbaijão' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Bahrein' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BY', label: 'Bielorrússia' },
  { value: 'BE', label: 'Bélgica' },
  { value: 'BZ', label: 'Belize' },
  { value: 'BJ', label: 'Benin' },
  { value: 'BO', label: 'Bolívia' },
  { value: 'BA', label: 'Bósnia e Herzegovina' },
  { value: 'BW', label: 'Botsuana' },
  { value: 'BN', label: 'Brunei' },
  { value: 'BG', label: 'Bulgária' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'BT', label: 'Butão' },
  { value: 'CV', label: 'Cabo Verde' },
  { value: 'CM', label: 'Camarões' },
  { value: 'KH', label: 'Camboja' },
  { value: 'CA', label: 'Canadá' },
  { value: 'QA', label: 'Catar' },
  { value: 'KZ', label: 'Cazaquistão' },
  { value: 'TD', label: 'Chade' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CY', label: 'Chipre' },
  { value: 'CO', label: 'Colômbia' },
  { value: 'KM', label: 'Comores' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Congo (Rep. Democrática)' },
  { value: 'KP', label: 'Coreia do Norte' },
  { value: 'KR', label: 'Coreia do Sul' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CI', label: 'Costa do Marfim' },
  { value: 'HR', label: 'Croácia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'DJ', label: 'Djibuti' },
  { value: 'DM', label: 'Dominica' },
  { value: 'EG', label: 'Egito' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'AE', label: 'Emirados Árabes Unidos' },
  { value: 'EC', label: 'Equador' },
  { value: 'ER', label: 'Eritreia' },
  { value: 'SK', label: 'Eslováquia' },
  { value: 'SI', label: 'Eslovênia' },
  { value: 'ES', label: 'Espanha' },
  { value: 'SZ', label: 'Essuatíni' },
  { value: 'EE', label: 'Estônia' },
  { value: 'ET', label: 'Etiópia' },
  { value: 'FJ', label: 'Fiji' },
  { value: 'PH', label: 'Filipinas' },
  { value: 'FI', label: 'Finlândia' },
  { value: 'FR', label: 'França' },
  { value: 'GA', label: 'Gabão' },
  { value: 'GM', label: 'Gâmbia' },
  { value: 'GH', label: 'Gana' },
  { value: 'GE', label: 'Geórgia' },
  { value: 'GD', label: 'Granada' },
  { value: 'GR', label: 'Grécia' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GN', label: 'Guiné' },
  { value: 'GW', label: 'Guiné-Bissau' },
  { value: 'GQ', label: 'Guiné Equatorial' },
  { value: 'GY', label: 'Guiana' },
  { value: 'HT', label: 'Haiti' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hungria' },
  { value: 'YE', label: 'Iêmen' },
  { value: 'IN', label: 'Índia' },
  { value: 'ID', label: 'Indonésia' },
  { value: 'IQ', label: 'Iraque' },
  { value: 'IR', label: 'Irã' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'IS', label: 'Islândia' },
  { value: 'IL', label: 'Israel' },
  { value: 'IT', label: 'Itália' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: 'Japão' },
  { value: 'JO', label: 'Jordânia' },
  { value: 'KI', label: 'Quiribati' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LA', label: 'Laos' },
  { value: 'LS', label: 'Lesoto' },
  { value: 'LV', label: 'Letônia' },
  { value: 'LB', label: 'Líbano' },
  { value: 'LR', label: 'Libéria' },
  { value: 'LY', label: 'Líbia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lituânia' },
  { value: 'LU', label: 'Luxemburgo' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malásia' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MV', label: 'Maldivas' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malta' },
  { value: 'MA', label: 'Marrocos' },
  { value: 'MH', label: 'Ilhas Marshall' },
  { value: 'MR', label: 'Mauritânia' },
  { value: 'MU', label: 'Maurício' },
  { value: 'MX', label: 'México' },
  { value: 'MM', label: 'Mianmar' },
  { value: 'FM', label: 'Micronésia' },
  { value: 'MZ', label: 'Moçambique' },
  { value: 'MD', label: 'Moldávia' },
  { value: 'MC', label: 'Mônaco' },
  { value: 'MN', label: 'Mongólia' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'NA', label: 'Namíbia' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NI', label: 'Nicarágua' },
  { value: 'NE', label: 'Níger' },
  { value: 'NG', label: 'Nigéria' },
  { value: 'NO', label: 'Noruega' },
  { value: 'NZ', label: 'Nova Zelândia' },
  { value: 'OM', label: 'Omã' },
  { value: 'NL', label: 'Países Baixos' },
  { value: 'PW', label: 'Palau' },
  { value: 'PA', label: 'Panamá' },
  { value: 'PG', label: 'Papua-Nova Guiné' },
  { value: 'PK', label: 'Paquistão' },
  { value: 'PY', label: 'Paraguai' },
  { value: 'PE', label: 'Peru' },
  { value: 'PL', label: 'Polônia' },
  { value: 'PT', label: 'Portugal' },
  { value: 'KE', label: 'Quênia' },
  { value: 'KG', label: 'Quirguistão' },
  { value: 'CF', label: 'República Centro-Africana' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'CZ', label: 'República Tcheca' },
  { value: 'RO', label: 'Romênia' },
  { value: 'RW', label: 'Ruanda' },
  { value: 'RU', label: 'Rússia' },
  { value: 'WS', label: 'Samoa' },
  { value: 'SM', label: 'San Marino' },
  { value: 'ST', label: 'São Tomé e Príncipe' },
  { value: 'KN', label: 'São Cristóvão e Neves' },
  { value: 'LC', label: 'Santa Lúcia' },
  { value: 'VC', label: 'São Vicente e Granadinas' },
  { value: 'SC', label: 'Seicheles' },
  { value: 'SN', label: 'Senegal' },
  { value: 'SL', label: 'Serra Leoa' },
  { value: 'RS', label: 'Sérvia' },
  { value: 'SG', label: 'Singapura' },
  { value: 'SY', label: 'Síria' },
  { value: 'SO', label: 'Somália' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SS', label: 'Sudão do Sul' },
  { value: 'SD', label: 'Sudão' },
  { value: 'SE', label: 'Suécia' },
  { value: 'CH', label: 'Suíça' },
  { value: 'SR', label: 'Suriname' },
  { value: 'TJ', label: 'Tajiquistão' },
  { value: 'TH', label: 'Tailândia' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TZ', label: 'Tanzânia' },
  { value: 'TL', label: 'Timor-Leste' },
  { value: 'TG', label: 'Togo' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad e Tobago' },
  { value: 'TN', label: 'Tunísia' },
  { value: 'TM', label: 'Turcomenistão' },
  { value: 'TR', label: 'Turquia' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UA', label: 'Ucrânia' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UY', label: 'Uruguai' },
  { value: 'UZ', label: 'Uzbequistão' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VA', label: 'Vaticano' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnã' },
  { value: 'ZM', label: 'Zâmbia' },
  { value: 'ZW', label: 'Zimbábue' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'MK', label: 'Macedônia do Norte' },
  { value: 'PS', label: 'Palestina' },
  { value: 'XK', label: 'Kosovo' },
]

PAISES.sort((a, b) => {
  if (a.value === 'BR') return -1
  if (b.value === 'BR') return 1
  return a.label.localeCompare(b.label, 'pt-BR')
})

export function isBrasil(paisId: string): boolean {
  return paisId === 'BR'
}
